"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*$)%nq=-3u#dobgbhb7l==#l^!2_eoa09lrn8b9njc@im(75no'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relationship_app',
    'bookshelf',  # <-- added your app here
]

AUTH_USER_MODEL = "bookshelf.CustomUser"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

INSTALLED_APPS += ['csp']

MIDDLEWARE = [
    # existing middleware...
    'csp.middleware.CSPMiddleware',
    # other middleware...
]

# Conservative CSP — adjust to add CDNs or other domains you trust
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)          # add third-party script hosts if needed
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # avoid 'unsafe-inline' if possible
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# SECURITY: production settings (set via env vars for real deploy)
import os

DEBUG = False  # MUST be False in production

# Ensure you set ALLOWED_HOSTS to your domain(s) in production
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Cookies over HTTPS only (in production when you have HTTPS)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Browser protections
SECURE_BROWSER_XSS_FILTER = True          # sets X-XSS-Protection header
SECURE_CONTENT_TYPE_NOSNIFF = True       # sets X-Content-Type-Options: nosniff
X_FRAME_OPTIONS = 'DENY'                 # prevents clickjacking

# Optional: redirect HTTP to HTTPS
SECURE_SSL_REDIRECT = True               # enable only if behind HTTPS

# HSTS (HTTP Strict Transport Security) - enable for production
SECURE_HSTS_SECONDS = 31536000           # 1 year; tune for your deploy
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Use secure session serializer (default is fine). Keep SECRET_KEY secret.
# Use environment variables to store sensitive config in production.


# SECURITY: HTTPS enforcement & secure cookies
# Only enable SECURE_SSL_REDIRECT and HSTS when your site is served over HTTPS (production)
SECURE_SSL_REDIRECT = True            # redirect all HTTP -> HTTPS
# If behind a reverse proxy/load balancer (e.g., nginx), use this to tell Django to trust X-Forwarded-Proto:
# (set this exactly to the header you set in your proxy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Ensure DEBUG = False in production (do not expose detailed tracebacks)
DEBUG = False

# IMPORTANT: set ALLOWED_HOSTS to the hostnames / domains used in production
ALLOWED_HOSTS = ['mydomain.com', 'www.mydomain.com']
